console.log(document.getElementById("app-title"));
console.log(document.getElementById("app-title").id);
console.log(document.getElementById("app-title").className);
console.log(document.getElementById("app-title").getAttribute("id"));
console.log(document.getElementById("app-title").getAttribute("class"));
document.getElementById("app-title").id="new-title";
document.getElementById("new-title").className="text-red";
const title=document.getElementById("new-title");
console.log(title.textContent);
title.textContent="hello world";
title.innerText="hello again";
title.innerHTML="<strong>Shopping List</strong>";
title.style.color="blue";
title.style.fontSize="40px";
title.style.backgroundColor="yellow";
console.log(document.querySelector("h1"));
console.log(document.querySelector("#new-title"));
console.log(document.querySelector(".container"));
console.log(document.querySelector("input[type='text']"));
console.log(document.querySelector("li:nth-child(2)"));
const secondItem = document.querySelector("li:nth-child(2)");
secondItem.innerText="Mango Juice";
secondItem.style.color="orange";
const list=document.querySelector("ul");
console.log(list);
firstItem=list.querySelector("li");
firstItem.style.color="purple";