let output;
output = document.all;
console.log(output);
output=document.domain;
output=document.URL;
output=document.doctype;
output=document.characterSet;
output=document.forms;
output=document.forms[0];
output=document.forms[0].id;
output=document.forms[0].method;
output=document.forms[0].action;
output=document.forms[0].id="new-id";
output=document.forms[0].id;
output=document.links;
output=document.links[0];
output=document.links[0].href;
output=document.links[0].href="https://facebook.com";
output=document.links[0].className="text-red";
output=document.links[0].classList;
output=document.images;
output=document.images[0];
output=document.images[0].src;
const forms=Array.from(document.forms);
forms.forEach((form)=>console.log(form));
console.log(output);
